### ISSUE TITLE
Deploying charm results in "Failed to configure instance for innodb"

### ISSUE THREAD

**Issue by jamesbeedy** [juju-solutions/charm-mysql#44] opened 2023-03-22 22:11 UTC
I get this message when deploying mysql from edge in a sphere cloud.

```bash
App           Version  Status   Scale  Charm         Channel   Rev  Exposed  Message
mysql                  blocked      1  mysql         edge      132  no       Failed to configure instance for InnoDB
mysql-router  8.0.32   blocked      1  mysql-router  8.0/edge   61  no       'db-router' incomplete, 'shared-db' missing, MySQL Router not yet bootstrapped
slurmctld     69a8126  blocked      1  slurmctld     edge       50  no       Machine needs reboot
slurmd        8800da8  blocked      1  slurmd        edge       60  no       Machine needs reboot
slurmdbd      b5b1f35  blocked      1  slurmdbd      edge       43  no       Machine needs reboot

Unit               Workload  Agent  Machine  Public address  Ports  Message
mysql/1*           blocked   idle   4        10.104.138.235         Failed to configure instance for InnoDB
slurmctld/0*       blocked   idle   1        10.104.138.19          Machine needs reboot
slurmd/0*          blocked   idle   0        10.104.139.16          Machine needs reboot
slurmdbd/0*        blocked   idle   2        10.104.138.230         Machine needs reboot
  mysql-router/0*  blocked   idle            10.104.138.230         'db-router' incomplete, 'shared-db' missing, MySQL Router not yet bootstrapped


```

The command I used: ```juju deploy mysql --channel edge --constraints "cores=2 mem=4G root-disk=20G" --series jammy```

This is what I see in the logs:
```bash
unit-mysql-1: 14:45:12 INFO juju.worker.uniter.operation ran "config-changed" hook (via hook dispatching script: dispatch)
unit-mysql-1: 14:45:12 INFO juju.worker.uniter found queued "start" hook
unit-mysql-1: 14:45:13 INFO unit.mysql/1.juju-log Running legacy hooks/start.
unit-mysql-1: 14:45:13 INFO unit.mysql/1.juju-log Retrieving the total memory of the server
unit-mysql-1: 14:45:20 ERROR unit.mysql/1.juju-log Failed to configure instance: 10.104.138.235 with error b'Cannot set LC_ALL to locale en_US.UTF-8: No such file or directory\nConfiguring local MySQL instance listening at port 3306 for use in an InnoDB cluster...\n\nThis instance reports its own address as \x1b[1mjuju-d4ca05-4:3306\x1b[0m\nClients and other cluster members will communicate with it through this address by default. If this is not correct, the report_host MySQL system variable should be changed.\n\x1b[31mERROR: \x1b[0mCannot use host \'juju-d4ca05-4\' for instance \'juju-d4ca05-4:3306\' because it resolves to an IP address (127.0.1.1) that does not match a real network interface, thus it is not supported. Change your system settings and/or set the MySQL server \'report_host\' variable to a hostname that resolves to a supported IP address.\nTraceback (most recent call last):\n  File "<string>", line 1, in <module>\nRuntimeError: Dba.configure_instance: Invalid host/IP \'juju-d4ca05-4\' resolves to \'127.0.1.1\' which is not supported.\n\n'
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/mysql_vm_helpers.py", line 493, in _run_mysqlsh_script
    return subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['charmed-mysql.mysqlsh', '--no-wizard', '--python', '-f', '/var/snap/charmed-mysql/common/tmpz3k2lver']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/mysql/v0/mysql.py", line 588, in configure_instance
    self._run_mysqlsh_script("\n".join(configure_instance_command))
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/mysql_vm_helpers.py", line 497, in _run_mysqlsh_script
    raise MySQLClientError(e.stderr)
charms.mysql.v0.mysql.MySQLClientError: b'Cannot set LC_ALL to locale en_US.UTF-8: No such file or directory\nConfiguring local MySQL instance listening at port 3306 for use in an InnoDB cluster...\n\nThis instance reports its own address as \x1b[1mjuju-d4ca05-4:3306\x1b[0m\nClients and other cluster members will communicate with it through this address by default. If this is not correct, the report_host MySQL system variable should be changed.\n\x1b[31mERROR: \x1b[0mCannot use host \'juju-d4ca05-4\' for instance \'juju-d4ca05-4:3306\' because it resolves to an IP address (127.0.1.1) that does not match a real network interface, thus it is not supported. Change your system settings and/or set the MySQL server \'report_host\' variable to a hostname that resolves to a supported IP address.\nTraceback (most recent call last):\n  File "<string>", line 1, in <module>\nRuntimeError: Dba.configure_instance: Invalid host/IP \'juju-d4ca05-4\' resolves to \'127.0.1.1\' which is not supported.\n\n'

```
Deploying on focal gives an different error

```bash
unit-mysql-0: 14:39:51 INFO juju.worker.uniter awaiting error resolution for "storage-attached" hook
unit-mysql-0: 14:39:51 WARNING unit.mysql/0.database-storage-attached /usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (3.0.4) doesn't match a supported version!
unit-mysql-0: 14:39:51 WARNING unit.mysql/0.database-storage-attached   warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
unit-mysql-0: 14:39:51 WARNING unit.mysql/0.database-storage-attached Traceback (most recent call last):
unit-mysql-0: 14:39:51 WARNING unit.mysql/0.database-storage-attached   File "./src/charm.py", line 23, in <module>
unit-mysql-0: 14:39:51 WARNING unit.mysql/0.database-storage-attached     from charms.mysql.v0.tls import MySQLTLS
unit-mysql-0: 14:39:51 WARNING unit.mysql/0.database-storage-attached   File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/mysql/v0/tls.py", line 30, in <module>
unit-mysql-0: 14:40:31 INFO juju.worker.uniter awaiting error resolution for "storage-attached" hook
unit-mysql-0: 14:40:31 WARNING unit.mysql/0.database-storage-attached /usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (3.0.4) doesn't match a supported version!
unit-mysql-0: 14:40:31 WARNING unit.mysql/0.database-storage-attached   warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
unit-mysql-0: 14:40:31 WARNING unit.mysql/0.database-storage-attached Traceback (most recent call last):
unit-mysql-0: 14:40:31 WARNING unit.mysql/0.database-storage-attached   File "./src/charm.py", line 23, in <module>
unit-mysql-0: 14:40:31 WARNING unit.mysql/0.database-storage-attached     from charms.mysql.v0.tls import MySQLTLS
unit-mysql-0: 14:40:31 WARNING unit.mysql/0.database-storage-attached   File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/mysql/v0/tls.py", line 30, in <module>
unit-mysql-0: 14:40:31 WARNING unit.mysql/0.database-storage-attached     from charms.tls_certificates_interface.v1.tls_certificates import (
unit-mysql-0: 14:40:31 WARNING unit.mysql/0.database-storage-attached   File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/tls_certificates_interface/v1/tls_certificates.py", line 257, in <module>
unit-mysql-0: 14:40:31 WARNING unit.mysql/0.database-storage-attached     from cryptography import x509
unit-mysql-0: 14:40:31 WARNING unit.mysql/0.database-storage-attached   File "/var/lib/juju/agents/unit-mysql-0/charm/venv/cryptography/x509/__init__.py", line 6, in <module>
unit-mysql-0: 14:40:31 WARNING unit.mysql/0.database-storage-attached     from cryptography.x509 import certificate_transparency
unit-mysql-0: 14:40:31 WARNING unit.mysql/0.database-storage-attached   File "/var/lib/juju/agents/unit-mysql-0/charm/venv/cryptography/x509/certificate_transparency.py", line 10, in <module>
unit-mysql-0: 14:40:31 WARNING unit.mysql/0.database-storage-attached     from cryptography.hazmat.bindings._rust import x509 as rust_x509
unit-mysql-0: 14:40:31 WARNING unit.mysql/0.database-storage-attached ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /var/lib/juju/agents/unit-mysql-0/charm/venv/cryptography/hazmat/bindings/_rust.abi3.so)

```
This charm seems to deploy just fine in my local lxd environment .... but fails on vsphere.

How could I investigate this further?

**Comment by kwmonroe** [comment] 2023-03-24 03:14
Heya @jamesbeedy!  Couple observations...

The charm you deployed doesn't live in this repo; in fact, this repo should have big red letters to warn people that the dragons here are `./hook`-based, even predating reactive charming.  Source for the charm you deployed (rev 132 from `mysql --channel edge`) lives in the [mysql-operator repo](https://github.com/canonical/mysql-operator).

But since we're here, I figured that charm must be tuned for lxd and all other cloud VMs would fail.  So I ran your command on aws, and dangit, it worked:
```
$ juju deploy mysql --channel edge --constraints "cores=2 mem=4G root-disk=20G" --series jammy
$ juju status
...
Model    Controller     Cloud/Region   Version  SLA          Timestamp
default  aws-us-east-1  aws/us-east-1  2.9.42   unsupported  20:45:25-05:00

App    Version  Status  Scale  Charm  Channel  Rev  Exposed  Message
mysql  8.0.32   active      1  mysql  edge     133  no       Primary

Unit      Workload  Agent  Machine  Public address  Ports               Message
mysql/0*  active    idle   0        52.91.177.189   3306/tcp,33060/tcp  Primary
```
Then i confirmed that I could fail just as good as you on vsphere:
```
Model  Controller   Cloud/Region    Version  SLA          Timestamp
bdx  vsphere-kwm  vsphere/Boston  2.9.42   unsupported  20:57:52-05:00

App    Version  Status   Scale  Charm  Channel  Rev  Exposed  Message
mysql           blocked      1  mysql  edge     133  no       Failed to configure instance for InnoDB

Unit      Workload  Agent  Machine  Public address  Ports  Message
mysql/0*  blocked   idle   0        10.246.154.232         Failed to configure instance for InnoDB
```
One difference I spotted (because the error said exactly this) is that my vsphere hostname resolved to loopback and my aws unit to a valid ip on a real interface.  I also noticed that mysqld itself seemed healthy on the vsphere unit even though the charm status was `blocked`. :shrug: At this point, it's probably best to move over to the [proper issue bucket](https://github.com/canonical/mysql-operator/issues).

Before you go, I see you're using the `mysql-router` subordinate. Perhaps worth looking at https://charmhub.io/mysql-innodb-cluster if you haven't already.  I know that duo works on vsphere because we use it for [vault in k8s](https://ubuntu.com/kubernetes/docs/encryption-at-rest) -- the downside of course being that you'll need 3 units for `m-i-c`.

Anyway, hope some of that helps.  I'm closing this out as invalid for this repo.

**Closed as not planned by kwmonroe** 2023-03-24 03:14 UTC

**Comment by jamesbeedy** [comment] 2023-03-24 04:56
🤦‍♂️thank you for the validation here. I’ll move this over to the correct repo now in that case.

**Comment by jamesbeedy** [comment] 2023-03-24 05:02
New bug https://github.com/canonical/mysql-operator/issues/new?assignees=&labels=bug&template=bug_report.md
